apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: cassandra-patient-deployment
spec:
  selector:
    matchLabels:
      app: cassandra-patient
  replicas: 1 
  template: 
    metadata:
      labels:
        app: cassandra-patient
    spec:
      containers:
      - name: cassandra-patient
        image: binu/golang-cassandra-patient:latest
        ports:
        - containerPort: 8080
